namespace InsurancePOC.Shared.Dtos;

/// <summary>
/// Data transfer object for creating a new client.
/// Excludes Id and CreatedAt as these are generated by the system.
/// </summary>
public class CreateClientDto
{
    public string FirstName { get; set; } = "";
    public string LastName { get; set; } = "";
    public string Email { get; set; } = "";
    public string? Phone { get; set; }
    public DateTime DateOfBirth { get; set; }
}